# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MessagingApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MessagingApp
pod 'XMPPFramework/Swift'
pod 'NoChat', '~> 0.3'
pod 'YYText'
pod 'HPGrowingTextView'

  target 'MessagingAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
